import Head from "next/head";
import Intro from "../components/Intro";
import Service from "../components/Services";
import styles from "../styles/Home.module.css";
import { data } from "../data";
import Testimonials from "../components/Testimonials";

export default function Home({ services }) {
  return (
    <>
      <Head>
        <title>Av0cad0 NextJs Single Page App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Intro />
      <Service services={services} />
      <Testimonials />
    </>
  );
}

export const getStaticProps = () => {
  const services = data;
  return {
    props: { services },
  };
};
